
import { KaizenEntry, KaizenSector, KaizenType, KaizenBenefit } from '../types';

export const mockKaizens: KaizenEntry[] = [
  {
    id: '1',
    title: 'Cải tiến bảng kẹp hồ sơ kỹ thuật',
    sector: KaizenSector.CONG_CU,
    unit: 'TNK',
    date: '2024-03-15',
    type: KaizenType.KAIZEN,
    beforeState: 'Bảng kẹp hồ sơ cũ bằng gỗ nặng, dễ làm trầy xước xe khách hàng khi để lên nắp capo.',
    beforeImages: ['https://picsum.photos/400/300?random=1', 'https://picsum.photos/400/300?random=11'],
    content: 'Thay thế bằng bảng kẹp nhựa mềm có lót cao su hít, giúp bảo vệ bề mặt sơn xe tuyệt đối.',
    afterImages: ['https://picsum.photos/400/300?random=12', 'https://picsum.photos/400/300?random=13'],
    benefits: [KaizenBenefit.CSL, KaizenBenefit.PROD],
    impactDescription: 'Khách hàng hài lòng hơn vì xe được bảo quản tốt, kỹ thuật viên thao tác nhanh hơn 10%.',
    cost: 150000,
    createdBy: 'user_contributor_1',
    createdAt: '2024-03-15T08:00:00Z',
    updatedAt: '2024-03-15T08:00:00Z',
    status: 'ACTIVE',
    history: []
  },
  {
    id: '2',
    title: 'Hệ thống nhắc hẹn bảo dưỡng tự động',
    sector: KaizenSector.QUY_TRINH,
    unit: 'HLAN',
    date: '2024-02-10',
    type: KaizenType.YOKOTEN,
    // Fix: targetUnit -> sourceUnit to match KaizenEntry interface
    sourceUnit: 'TNK',
    beforeState: 'Nhân viên phải gọi điện thủ công nhắc khách hàng, tốn nhiều thời gian và dễ bỏ sót.',
    beforeImages: ['https://picsum.photos/400/300?random=2'],
    content: 'Áp dụng quy trình từ TNK, sử dụng bảng excel macro để tự động lọc và gửi SMS nhắc hẹn.',
    afterImages: ['https://picsum.photos/400/300?random=21'],
    benefits: [KaizenBenefit.PROD, KaizenBenefit.CSL, KaizenBenefit.COST],
    impactDescription: 'Giảm 70% thời gian nhân viên trực tổng đài, tỷ lệ khách quay lại tăng 15%.',
    cost: 0,
    createdBy: 'admin_1',
    createdAt: '2024-02-10T14:30:00Z',
    updatedAt: '2024-02-10T14:30:00Z',
    status: 'ACTIVE',
    history: []
  },
  {
    id: '3',
    title: 'Sắp xếp kho phụ tùng theo mã màu 5S',
    sector: KaizenSector.NAMS,
    unit: 'MVL',
    date: '2024-04-01',
    type: KaizenType.KAIZEN,
    beforeState: 'Phụ tùng để lộn xộn, tìm kiếm mất trung bình 5 phút cho mỗi món.',
    beforeImages: ['https://picsum.photos/400/300?random=3'],
    content: 'Sơn lại các kệ theo phân loại hàng (Fast moving, Slow moving) và dán nhãn 5S.',
    afterImages: ['https://picsum.photos/400/300?random=31', 'https://picsum.photos/400/300?random=32'],
    benefits: [KaizenBenefit.NAMS, KaizenBenefit.PROD, KaizenBenefit.ESL],
    impactDescription: 'Thời gian tìm kiếm giảm xuống còn dưới 30 giây.',
    cost: 2000000,
    createdBy: 'user_contributor_2',
    createdAt: '2024-04-01T09:15:00Z',
    updatedAt: '2024-04-01T09:15:00Z',
    status: 'ACTIVE',
    history: []
  },
  {
    id: '4',
    title: 'Lắp đặt gương cầu lồi tại góc cua xưởng dịch vụ',
    sector: KaizenSector.ATLD,
    unit: 'TTG',
    date: '2024-05-05',
    type: KaizenType.KAIZEN,
    beforeState: 'Góc cua khu vực xưởng hẹp, khuất tầm nhìn, dễ xảy ra va chạm khi xe ra vào.',
    beforeImages: ['https://picsum.photos/400/300?random=4'],
    content: 'Lắp đặt gương cầu lồi đường kính 60cm tại 2 góc khuất chính.',
    afterImages: ['https://picsum.photos/400/300?random=41'],
    benefits: [KaizenBenefit.ATLD, KaizenBenefit.CSL],
    impactDescription: 'Triệt tiêu 100% các tình huống suýt va chạm tại khu vực này.',
    cost: 1200000,
    createdBy: 'staff',
    createdAt: '2024-05-05T10:00:00Z',
    updatedAt: '2024-05-05T10:00:00Z',
    status: 'ACTIVE',
    history: []
  },
  {
    id: '5',
    title: 'Bản đồ hướng dẫn khách hàng tự động bằng QR Code',
    sector: KaizenSector.CSVC,
    unit: 'TBT',
    date: '2024-05-12',
    type: KaizenType.KAIZEN,
    beforeState: 'Khách hàng thường xuyên hỏi đường đi nhà vệ sinh, khu vực cafe, quầy thu ngân.',
    beforeImages: ['https://picsum.photos/400/300?random=5'],
    content: 'Dán QR code tại các bàn chờ khách hàng, quét mã sẽ hiện sơ đồ showroom sinh động.',
    afterImages: ['https://picsum.photos/400/300?random=51'],
    benefits: [KaizenBenefit.CSL, KaizenBenefit.PROD],
    impactDescription: 'Giảm 50% các câu hỏi chỉ đường lặp đi lặp lại cho nhân viên lễ tân.',
    cost: 50000,
    createdBy: 'staff',
    createdAt: '2024-05-12T15:00:00Z',
    updatedAt: '2024-05-12T15:00:00Z',
    status: 'ACTIVE',
    history: []
  },
  {
    id: '6',
    title: 'Thùng phân loại rác thải nguy hại tại chỗ',
    sector: KaizenSector.KHAC,
    unit: 'TAS',
    date: '2024-05-20',
    type: KaizenType.KAIZEN,
    beforeState: 'Giẻ lau dầu mỡ và rác sinh hoạt thường bị bỏ chung, gây khó khăn cho việc xử lý môi trường.',
    beforeImages: ['https://picsum.photos/400/300?random=6'],
    content: 'Thiết kế bộ thùng rác 2 màu kèm biển báo hướng dẫn phân loại ngay tại mỗi khoang sửa chữa.',
    afterImages: ['https://picsum.photos/400/300?random=61'],
    benefits: [KaizenBenefit.ENV, KaizenBenefit.NAMS, KaizenBenefit.ATLD],
    impactDescription: 'Đảm bảo tuân thủ 100% quy định về quản lý chất thải nguy hại.',
    cost: 800000,
    createdBy: 'staff',
    createdAt: '2024-05-20T09:00:00Z',
    updatedAt: '2024-05-20T09:00:00Z',
    status: 'ACTIVE',
    history: []
  },
  {
    id: '7',
    title: 'Giá treo súng hơi tự động thu hồi',
    sector: KaizenSector.CONG_CU,
    unit: 'HPTN',
    date: '2024-06-01',
    type: KaizenType.KAIZEN,
    beforeState: 'Dây súng hơi thường vứt dưới sàn, dễ bị xe cán qua làm hỏng dây và gây vấp ngã.',
    beforeImages: ['https://picsum.photos/400/300?random=7'],
    content: 'Lắp đặt puly và đối trọng giúp dây súng tự động kéo lên cao khi không sử dụng.',
    afterImages: ['https://picsum.photos/400/300?random=71'],
    benefits: [KaizenBenefit.PROD, KaizenBenefit.NAMS, KaizenBenefit.ATLD],
    impactDescription: 'Tăng tuổi thọ dây hơi thêm 2 lần, sàn xưởng gọn gàng sạch sẽ.',
    cost: 350000,
    createdBy: 'staff',
    createdAt: '2024-06-01T11:00:00Z',
    updatedAt: '2024-06-01T11:00:00Z',
    status: 'ACTIVE',
    history: []
  },
  {
    id: '8',
    title: 'Quy trình kiểm tra xe 2 người phối hợp (Shadowing)',
    sector: KaizenSector.QUY_TRINH,
    unit: 'HBHA',
    date: '2024-06-10',
    type: KaizenType.KAIZEN,
    beforeState: '1 người kiểm tra xe mất 15 phút, dễ bỏ sót các lỗi nhỏ ở phía đối diện.',
    beforeImages: ['https://picsum.photos/400/300?random=8'],
    content: 'Áp dụng mô hình Shadowing: 2 kỹ thuật viên di chuyển đối xứng quanh xe.',
    afterImages: ['https://picsum.photos/400/300?random=81'],
    benefits: [KaizenBenefit.PROD, KaizenBenefit.CSL],
    impactDescription: 'Thời gian kiểm tra giảm còn 8 phút, độ chính xác tăng 20%.',
    cost: 0,
    createdBy: 'staff',
    createdAt: '2024-06-10T14:00:00Z',
    updatedAt: '2024-06-10T14:00:00Z',
    status: 'ACTIVE',
    history: []
  },
  {
    id: '9',
    title: 'Đèn báo trạng thái khoang sửa chữa (Xanh/Đỏ)',
    sector: KaizenSector.CSVC,
    unit: 'TNK',
    date: '2024-06-15',
    type: KaizenType.KAIZEN,
    beforeState: 'Quản đốc khó quan sát khoang nào đang trống để điều phối xe vào.',
    beforeImages: ['https://picsum.photos/400/300?random=9'],
    content: 'Lắp hệ thống đèn LED cảm biến tại mỗi khoang, kết nối về bảng điều khiển trung tâm.',
    afterImages: ['https://picsum.photos/400/300?random=91'],
    benefits: [KaizenBenefit.PROD, KaizenBenefit.CSL],
    impactDescription: 'Quản đốc điều xe nhanh hơn, giảm thời gian xe chờ tại cổng xưởng.',
    cost: 4500000,
    createdBy: 'staff',
    createdAt: '2024-06-15T08:00:00Z',
    updatedAt: '2024-06-15T08:00:00Z',
    status: 'ACTIVE',
    history: []
  },
  {
    id: '10',
    title: 'Thiết kế bộ kit sửa chữa lưu động siêu gọn',
    sector: KaizenSector.CONG_CU,
    unit: 'MVL',
    date: '2024-06-20',
    type: KaizenType.KAIZEN,
    beforeState: 'Thùng đồ nghề cứu hộ cũ quá cồng kềnh, nhân viên đi xe máy rất khó mang vác.',
    beforeImages: ['https://picsum.photos/400/300?random=10'],
    content: 'Sử dụng túi vải chuyên dụng đa ngăn, phân loại dụng cụ theo bộ lẻ thường dùng.',
    afterImages: ['https://picsum.photos/400/300?random=101'],
    benefits: [KaizenBenefit.PROD, KaizenBenefit.ESL],
    impactDescription: 'Trọng lượng giảm 4kg, kích thước giảm 40%, cơ động hơn khi đi cứu hộ.',
    cost: 600000,
    createdBy: 'staff',
    createdAt: '2024-06-20T16:00:00Z',
    updatedAt: '2024-06-20T16:00:00Z',
    status: 'ACTIVE',
    history: []
  }
];
